apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: $(ARGOCD_URL)
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: fd43b1e770612fb89f08
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: DasHeistApartment
            teams:
            - deployment-admins
          teamNameField: both
