apiVersion: v1
kind: ConfigMap
metadata:
  namespace: argocd
  name: argocd-cm
data:
  admin.enabled: "false"
  url: https://argo-cd.crazypokemondev.de
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: fd43b1e770612fb89f08
          clientSecret: $$argocd-dex-secret:dex.github.clientSecret
          orgs:
          - name: DasHeistApartment
            teams:
            - deployment-admins
          teamNameField: both
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: argocd
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: argocd
  name: argocd-rbac-cm
data:
  policy.csv: |
    g, DasHeistApartment:deployment-admins, role:admin
  policy.default: role:readonly
  scopes: '[groups, email]'