apiVersion: v1
kind: Secret
metadata:
  name: argocd-dex-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  dex.github.clientSecret: ${argocd_github_app_secret}
