apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    name: 'in-cluster'
  sourceRepos:
  - 'https://github.com/DasHeistApartment/servah-gitops'