apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-root
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: in-cluster
  source:
    directory:
      recurse: true
    path: root
    repoURL: 'https://github.com/DasHeistApartment/servah-gitops'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
