apiVersion: v1
kind: Namespace
metadata:
  name: arc-runners
---
apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  namespace: arc-runners
type: Opaque
stringData:
  github_token: ${github_token}
