apiVersion: v1
kind: Namespace
metadata:
  name: dex
---
apiVersion: v1
kind: Secret
metadata:
  name: client-secrets
  namespace: dex
type: Opaque
stringData:
  headlamp: ${dex_headlamp_client_secret}
---
apiVersion: v1
kind: Namespace
metadata:
  name: headlamp
---
apiVersion: v1
kind: Secret
metadata:
  name: oidc
  namespace: headlamp
type: Opaque
stringData:
  clientID: headlamp
  clientSecret: ${dex_headlamp_client_secret}
  issuerURL: https://oidc.crazypokemondev.de
