apiVersion: v1
kind: Namespace
metadata:
  name: dex
---
apiVersion: v1
kind: Secret
metadata:
  name: client-secrets
  namespace: dex
type: Opaque
stringData:
  headlamp: ${dex_headlamp_client_secret}
