apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.csv: |
    g, DasHeistApartment:deployment-admins, role:admin
  policy.default: role:readonly
  scopes: '[groups, email]'