apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argo-cd.crazypokemondev.de
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: fd43b1e770612fb89f08
          clientSecret: $argocd-dex-secret:dex.github.clientSecret
          orgs:
          - name: DasHeistApartment
            teams:
            - deployment-admins
          teamNameField: both
