name: Terraform Plan/Apply (general)

on:
  push:
    branches:
      - main
    paths:
      - 'general/**'
  pull_request:
    branches:
      - main
    paths:
      - 'general/**'

jobs:
  plan:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/terraform-plan.yml
    with:
      environment: general
      use-public-runner: true
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit
  apply:
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: general
      use-public-runner: true
    permissions:
      contents: read
    secrets: inherit