name: Terraform Plan/Apply (kubernetes)

on:
  push:
    branches:
      - main
    paths:
      - 'kubernetes/**'
  pull_request:
    branches:
      - main
    paths:
      - 'kubernetes/**'

jobs:
  plan:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/terraform-plan.yml
    with:
      environment: kubernetes
    permissions:
      contents: read
      pull-requests: write
  apply:
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: kubernetes
    permissions:
      contents: read